architecture-beta
  group platform(cloud)[Platform]
  service browser(internet)[Browser] in platform
  service api(server)[API] in platform
  service database(database)[Database] in platform
  browser:R --> L:api
  api:R --> L:database
